version: "3.8"
services:
  client:
    image: who-nba-i
    build:
      dockerfile: Dockerfile.dev
    container_name: who-nba-c
    volumes:
      - ./:/client
      - node_modules:/node_modules/
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
volumes:
  node_modules:
